on:
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write
  pages: write

jobs:

  build-html:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: pip install Jinja2
    
    - name: Build HTML page
      run: python render_html.py --template default --out html/index.html resume_data.json

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Print to pdf
      run: |
        cd html
        sudo cp static/fonts/* /usr/local/share/fonts
        google-chrome --no-sandbox --headless --disable-gpu --print-to-pdf --no-pdf-header-footer file://$(pwd)/index.html
        mv output.pdf keating-resume.pdf
        ls

    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'html'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
